# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
config.vm.define :apache do |web|
	web.vm.box = "ubuntu/trusty64"
	#web.vm.provision :shell, path: "config_web.sh"
	#web.vm.hostname = "srv-web"
    #web.vm.network :forwarded_port, guest: 80, host: 4567
    #web.vm.network "public_network", bridge: "en0: WLAN (AirPort)"

  config.vm.define "jk1" do |j1|
    c7.vm.box = "jk/1"
  end

  config.vm.define "jk2" do | j2|
    c6.vm.box = "jk/2"
  end

end

	# config.vm.box_check_update = false
	# config.vm.network "forwarded_port", guest: 80, host: 8080
	# config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
	# config.vm.network "private_network", ip: "192.168.11.20"
	# config.vm.network "public_network"
	# config.vm.synced_folder "../data", "/vagrant_data"

	config.vm.provider "virtualbox" do |vb|
	# vb.gui = true
	vb.memory = "1024"
end
	# config.vm.provision :shell, inline: <<-SHELL
	# apt-get update
	# apt-get install -y apache2
	# SHELL
end
